"""
Write the OpenFOAM dictionaries (0/, constant/, system/) for the tandem case.

usage: python3 setup_case.py <caseDir> <nProcs> <maxIter>
"""
import os
import sys

import params as P

HDR = """/*--------------------------------*- C++ -*----------------------------------*\\
  Tandem airfoil S1223 + NACA 0009 - generated by scripts/setup_case.py
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       %s;
    location    "%s";
    object      %s;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def write(case, loc, name, body, cls="dictionary"):
    d = os.path.join(case, loc)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, name), "w") as f:
        f.write(HDR % (cls, loc, name) + body)


def field(case, name, cls, dim, internal, bcs):
    body = "dimensions      %s;\n\ninternalField   %s;\n\nboundaryField\n{\n" % (dim, internal)
    for patch, bc in bcs.items():
        body += "    %s\n    {\n" % patch
        for line in bc.strip().split("\n"):
            body += "        %s\n" % line.strip()
        body += "    }\n"
    body += "}\n"
    write(case, "0", name, body, cls)


def zero(case):
    U = "uniform (%.6g 0 0)" % P.U_INF
    empty = "type empty;"
    walls = lambda bc: {"airfoil1": bc, "airfoil2": bc}

    def bcs(far, out, wall):
        d = {"farfield": far, "outlet": out}
        d.update(walls(wall))
        d["frontAndBack"] = empty
        return d

    field(case, "U", "volVectorField", "[0 1 -1 0 0 0 0]", U, bcs(
        "type freestreamVelocity;\nfreestreamValue %s;\nvalue %s;" % (U, U),
        "type inletOutlet;\ninletValue %s;\nvalue %s;" % (U, U),
        "type noSlip;"))
    field(case, "p", "volScalarField", "[0 2 -2 0 0 0 0]", "uniform 0", bcs(
        "type freestreamPressure;\nfreestreamValue uniform 0;\nvalue uniform 0;",
        "type fixedValue;\nvalue uniform 0;",
        "type zeroGradient;"))

    def scalar(name, dim, val, wall):
        v = "uniform %.6g" % val
        field(case, name, "volScalarField", dim, v, bcs(
            "type inletOutlet;\ninletValue %s;\nvalue %s;" % (v, v),
            "type inletOutlet;\ninletValue %s;\nvalue %s;" % (v, v), wall))

    scalar("k", "[0 2 -2 0 0 0 0]", P.K_INF, "type fixedValue;\nvalue uniform 1e-14;")
    scalar("omega", "[0 0 -1 0 0 0 0]", P.OMEGA_INF,
           "type omegaWallFunction;\nvalue uniform %.6g;" % P.OMEGA_INF)
    scalar("ReThetat", "[0 0 0 0 0 0 0]", P.RETHETA_INF, "type zeroGradient;")
    scalar("gammaInt", "[0 0 0 0 0 0 0]", 1.0, "type zeroGradient;")
    field(case, "nut", "volScalarField", "[0 2 -1 0 0 0 0]", "uniform %.6g" % P.NUT_INF, bcs(
        "type calculated;\nvalue uniform %.6g;" % P.NUT_INF,
        "type calculated;\nvalue uniform %.6g;" % P.NUT_INF,
        "type nutLowReWallFunction;\nvalue uniform 0;"))


def constant(case):
    write(case, "constant", "transportProperties",
          "transportModel  Newtonian;\n\nnu              %.6g;\n" % P.NU)
    write(case, "constant", "turbulenceProperties", """simulationType  RAS;

RAS
{
    RASModel        kOmegaSSTLM;    // k-omega SST + gamma-ReTheta_t transition (Langtry-Menter)
    turbulence      on;
    printCoeffs     on;

    kOmegaSSTLMCoeffs
    {
        // keep the free-stream turbulence from decaying between the far field
        // and the airfoils (Spalart-Rumsey ambient source terms)
        decayControl    yes;
        kInf            %.6g;
        omegaInf        %.6g;
    }
}
""" % (P.K_INF, P.OMEGA_INF))


def force_coeffs(name, patches, chord, cofr_x):
    return """    %s
    {
        type            forceCoeffs;
        libs            ("libforces.so");
        writeControl    timeStep;
        writeInterval   1;
        log             false;
        patches         (%s);
        rho             rhoInf;
        rhoInf          %.6g;
        liftDir         (0 1 0);
        dragDir         (1 0 0);
        CofR            (%.6g 0 0);
        pitchAxis       (0 0 -1);       // positive = nose-up
        magUInf         %.6g;
        lRef            %.6g;
        Aref            %.6g;
    }
""" % (name, " ".join(patches), P.RHO, cofr_x, P.U_INF, chord, chord * P.SPAN)


def system(case, nprocs, max_iter):
    funcs = force_coeffs("coeffs_S1223", ["airfoil1"], P.C1, P.X_LE1 + 0.25 * P.C1)
    funcs += force_coeffs("coeffs_NACA0009", ["airfoil2"], P.C2, P.X_LE2 + 0.25 * P.C2)
    funcs += force_coeffs("coeffs_total", ["airfoil1", "airfoil2"], P.C1, P.X_LE1 + 0.25 * P.C1)
    funcs += """    yPlus
    {
        type            yPlus;
        libs            ("libfieldFunctionObjects.so");
        writeControl    writeTime;
    }
    wallShearStress
    {
        type            wallShearStress;
        libs            ("libfieldFunctionObjects.so");
        patches         (airfoil1 airfoil2);
        writeControl    writeTime;
    }
"""
    write(case, "system", "controlDict", """application     simpleFoam;

startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         %d;
deltaT          1;

writeControl    timeStep;
writeInterval   %d;
purgeWrite      2;
writeFormat     ascii;
writePrecision  10;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;

functions
{
%s}
""" % (max_iter, max(max_iter // 4, 50), funcs))

    write(case, "system", "fvSchemes", """ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         cellLimited Gauss linear 1;
}

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss limitedLinear 1;
    div(phi,omega)  bounded Gauss limitedLinear 1;
    div(phi,ReThetat) bounded Gauss limitedLinear 1;
    div(phi,gammaInt) bounded Gauss limitedLinear 1;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear limited corrected 0.5;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         limited corrected 0.5;
}

wallDist
{
    method          meshWave;
}
""")

    write(case, "system", "fvSolution", """solvers
{
    p
    {
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-9;
        relTol          0.05;
    }
    "(U|k|omega|ReThetat|gammaInt)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-10;
        relTol          0.1;
    }
}

SIMPLE
{
    consistent      yes;
    nNonOrthogonalCorrectors 1;
}

relaxationFactors
{
    fields
    {
        p               %g;
    }
    equations
    {
        U               %g;
        "(k|omega)"     %g;
        "(ReThetat|gammaInt)" %g;
    }
}
""" % (P.RELAX_P, P.RELAX_U, P.RELAX_TURB, P.RELAX_TRANS))

    write(case, "system", "decomposeParDict", """numberOfSubdomains %d;

method          scotch;
""" % nprocs)


if __name__ == "__main__":
    case = sys.argv[1]
    nprocs = int(sys.argv[2]) if len(sys.argv) > 2 else 8
    max_iter = int(sys.argv[3]) if len(sys.argv) > 3 else P.MAX_ITER
    zero(case)
    constant(case)
    system(case, nprocs, max_iter)
    print("case dictionaries written to", case)
